os: linux
dist: bionic
language: dart

before_install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test
# after_success:
  # - coveralls --exclude *test.cpp --exclude ${gtest_dir} --gcov-options '\-lpbc'

