os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
git:
  depth: 3
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b master
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
# safelist
branches:
  only:
    - master
    - testBench

