language: dart
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
git:
  depth: 3
cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b master
  - ./flutter/bin/flutter doctor
  - gem install coveralls-lcov

matrix:
  include:
    - name: Test
      env: COMMAND="test --coverage"
    - name: Analyze
      env: COMMAND="analyze"
script:
  - ./flutter/bin/flutter $COMMAND
after_success:
  - coveralls-lcov coverage/lcov.info
branches:
  only:
    - master
    - testBench