include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - camel_case_types
    - prefer_expression_function_bodies
    - prefer_typing_uninitialized_variables