include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - [build/**]
    - bin/cache/**
    - flutter/bin/cache/**
    - lib/exclude_me/*.exclude.dart
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    - camel_case_types
    - prefer_expression_function_bodies
    - prefer_typing_uninitialized_variables